agent:
    load: False
    load_as: 'saved_models/good_90_eps.msh'
    batch_size: 64
    #target_update_frequency: 50
    target_update_frequency: 100
    #initial_replay_memory: 50
    initial_replay_memory: 10000
    max_replay_size: 100000

nn:
    hidden_size: 5

optimizer:
    lr: .00025

# Training schedule
learning:
    epochs: 100
    train_episodes: 10
    train_frequency: 4

results:
    save_results: True
    dataset: True
    q_values: True
    links_report: True
    nodes_report: False

model:
    save_model: True
    save_as: '1000_eps-13dec2022'