agent:
    load: True
    load_as: 'saved_models/good_90_eps.msh'
    batch_size: 64
    target_update_frequency: 50
    initial_replay_memory: 5000
    max_replay_size: 100000

nn:
    hidden_size: 5

optimizer:
    lr: .00025

learning:
    epochs: 0
    train_episodes: 10
    train_frequency: 4

results:
    save_results: True
    dataset: True
    q_values: False
    links_report: True
    nodes_report: False

model:
    save_model: False
    save_as: 'good_90_eps'